# Generated by Django 2.2.15 on 2020-08-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='team',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
