# Generated by Django 2.2.15 on 2020-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200823_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cw_private',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CW private key'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cw_public',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CW public key'),
        ),
    ]
