# Generated by Django 2.2.15 on 2020-09-01 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200823_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', related_query_name='team', to='teams.Team'),
        ),
    ]
