# Generated by Django 2.2.15 on 2020-09-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200901_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='report_admin',
            field=models.BooleanField(default=False, verbose_name='Report Admin'),
        ),
    ]
