from django.urls import path

from . import views

app_name = "projects"
urlpatterns = [
    path("", views.ProjectListCreate.as_view(), name="project-list"),
    path("choices/", views.ProjectStatusChoicesList.as_view(),
         name="project-choices-list"),
    path("user/", views.UserProjectList.as_view(), name="user-projects-list"),
    path("<pk>/", views.ProjectRetrieveUpdateDelete.as_view(),
         name="project-retrieve"),
    path("<project_id>/clients/", views.ProjectClientListCreate.as_view(),
         name="project-clients-list"),
    path("<project_id>/members/", views.ProjectMemberListCreate.as_view(),
         name="project-members-list"),
    path("<project_id>/updates/", views.ProjectUpdateListCreate.as_view(),
         name="project-updates-list"),
    path("<project_id>/tasks/", views.ProjectTaskListCreate.as_view(),
         name="project-tasks-list"),
    path("clients/<pk>/", views.ClientRetrieveUpdateDelete.as_view(),
         name="client-retrieve"),
    path("members/<pk>/", views.MemberRetrieveUpdateDelete.as_view(),
         name="member-retrieve"),
    path("tasks/user/", views.UserTaskList.as_view(), name="user-tasks-list"),
    path("tasks/<pk>/", views.TaskRetrieveUpdateDelete.as_view(),
         name="task-retrieve"),
    path("tasks/<pk>/assign_self/",
         views.TaskAssignSelf.as_view(), name="task-assign-self"),
    path("tasks/<pk>/complete/", views.TaskComplete.as_view(), name="task-complete"),
    path("tasks/<pk>/uncomplete/",
         views.TaskUncomplete.as_view(), name="task-uncomplete"),
    path("tasks/<pk>/members/", views.TaskMemberListCreate.as_view(),
         name="task-members-list"),
    path("task_members/<pk>/", views.TaskMemberRetrieveUpdateDelete.as_view(),
         name="task-member-retrieve"),
    path("updates/all/", views.UpdateListCreate.as_view(), name="updates-list"),
    path("updates/all/<status>/", views.UpdateStatusList.as_view(),
         name="updates-status-list"),
    path("updates/choices/", views.UpdateStatusChoicesList.as_view(),
         name="update-choices-list"),
    path("updates/user/", views.UserUpdatesList.as_view(),
         name="user-updates-list"),
    path("updates/user/<status>/", views.UserUpdatesStatusList.as_view(),
         name="user-updates-status-list"),
    path("updates/<pk>/", views.UpdateRetrieveUpdateDelete.as_view(),
         name="update-retrieve"),
]
