# Generated by Django 2.2.15 on 2020-08-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('company_id', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('INSTALL', 'Installation'), ('SALES', 'Sales'), ('SERVICE', 'Service Trip'), ('TRAINING', 'Training')], max_length=255)),
                ('description', models.TextField()),
                ('billable', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('pictures', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('satisfied', models.BooleanField(default=False)),
                ('tested', models.BooleanField(default=False)),
                ('summary', models.TextField()),
                ('signature', models.FileField(upload_to='uploads/signatures/<django.db.models.fields.charfield>/<django.db.models.fields.charfield>-%Y%m%d%H%M')),
            ],
        ),
    ]
