# Generated by Django 2.2.15 on 2020-09-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default='Buford, GA', max_length=255),
            preserve_default=False,
        ),
    ]
