# Generated by Django 2.2.15 on 2020-08-27 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('company_id', models.PositiveIntegerField()),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customerservice',
            options={'verbose_name': 'Customer Service', 'verbose_name_plural': 'Customer Service Reports'},
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='signature',
            field=models.FileField(upload_to='uploads/signatures/%Y%m%d%H%M'),
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', related_query_name='time_record', to='reports.Report')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customerservice',
            name='report_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.Report'),
            preserve_default=False,
        ),
    ]
