# Generated by Django 2.2.15 on 2020-08-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200827_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Time Entry', 'verbose_name_plural': 'Time Entries'},
        ),
        migrations.CreateModel(
            name='InventoryCheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_checkouts', related_query_name='inventory_checkout', to='reports.Report')),
            ],
            options={
                'verbose_name': 'Inventory Check Out',
                'verbose_name_plural': 'Inventory Check Outs',
            },
        ),
    ]
