# Generated by Django 2.2.15 on 2020-09-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20200823_0219'),
        ('reports', '0002_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='team',
            field=models.ForeignKey(default='2b9296a5-cbde-4ebe-9fe5-3969106d7cd9', on_delete=django.db.models.deletion.CASCADE, related_name='reports', related_query_name='report', to='teams.Team'),
            preserve_default=False,
        ),
    ]
