# Generated by Django 2.2.15 on 2020-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200827_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('CUSTOMER_SERVICE', 'Customer Service')], default='CUSTOMER_SERVICE', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerservice',
            name='service_type',
            field=models.CharField(choices=[('INSTALL', 'Installation'), ('SALES', 'Sales'), ('SERVICE', 'Service Trip'), ('TRAINING', 'Training')], max_length=255, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_id',
            field=models.PositiveIntegerField(verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='company_name',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
    ]
