# Generated by Django 2.2.15 on 2020-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_customerservice_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerservice',
            name='service_type',
            field=models.CharField(choices=[('INSTALL', 'Installation'), ('MENU CHANGES', 'Menu Changes'), ('SALES', 'Sales'), ('SERVICE', 'Service Trip'), ('TRAINING', 'Training'), ('OTHER', 'Other')], max_length=255, verbose_name='Service Type'),
        ),
    ]
