# Generated by Django 2.2.15 on 2020-08-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200827_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='signature',
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/signatures/')),
                ('company', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signatures', related_query_name='signature', to='reports.Report')),
            ],
        ),
    ]
