# Generated by Django 2.2.15 on 2020-08-28 20:00

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200828_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='report',
        ),
        migrations.AddField(
            model_name='customerservice',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_service_reports', related_query_name='customer_service_report', to='reports.Signature'),
        ),
        migrations.AlterField(
            model_name='signature',
            name='file',
            field=models.ImageField(upload_to=reports.models.folder),
        ),
    ]
