# Generated by Django 2.2.15 on 2020-08-28 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0008_auto_20200828_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_reports', related_query_name='edited_report', to=settings.AUTH_USER_MODEL),
        ),
    ]
