# Generated by Django 2.2.15 on 2020-08-31 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_reports', related_query_name='edited_report', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
