# Generated by Django 2.2.15 on 2020-08-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
