# Generated by Django 2.2.15 on 2020-08-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200818_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cw_company',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
