# Generated by Django 2.2.15 on 2020-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_cw_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cw_company',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='CW company'),
        ),
    ]
