# Generated by Django 2.2.15 on 2020-10-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_ref',
            field=models.CharField(blank=True, max_length=255, verbose_name='Logo Ref'),
        ),
    ]
