# Generated by Django 2.2.15 on 2020-10-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_logo_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_ref',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logo Ref'),
        ),
    ]
