# Generated by Django 2.2.15 on 2020-11-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_auto_20201022_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stale_report_age',
            field=models.PositiveSmallIntegerField(default=7),
        ),
    ]
