# Generated by Django 2.2.15 on 2021-03-24 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210323_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('IN PROGRESS', 'In Progress'), ('AWAITING CUSTOMER', 'Awaiting Customer'), ('AWAITING SUPPORT', 'Awaiting Support'), ('UNDER REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PROPOSED', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskmember',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
