# Generated by Django 2.2.15 on 2021-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
