# Generated by Django 2.2.15 on 2021-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20210324_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskmember',
            options={'verbose_name': 'Task Member', 'verbose_name_plural': 'Task Members'},
        ),
        migrations.AddField(
            model_name='update',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
