# Generated by Django 2.2.15 on 2021-03-24 15:06

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20210324_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['primary', 'client_name']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['account__last_name', 'account__first_name']},
        ),
        migrations.AlterModelOptions(
            name='taskmember',
            options={'ordering': ['account__last_name', 'account__first_name'], 'verbose_name': 'Task Member', 'verbose_name_plural': 'Task Members'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('client_id', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('project', 'account')},
        ),
        migrations.AlterUniqueTogether(
            name='taskmember',
            unique_together={('task', 'account')},
        ),
    ]
