# Generated by Django 2.2.15 on 2021-03-24 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210324_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
