# Generated by Django 2.2.15 on 2021-04-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_task_completed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-primary', 'client_name']},
        ),
    ]
